spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/servicedb
    username: root
    password: ""
server:
  port: 9090

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    tags:
      application: productservice

couponService:
  url: http://localhost:9091/couponapi/coupons/

